export type SourceType = 'faq' | 'small_talk' | 'knowledge_qa'
export type MessageRole = 'user' | 'assistant' | 'agent' | 'system'
export type HandoffState = 'none' | 'waiting' | 'in_progress'
export type TicketStatus = 'pending' | 'processing' | 'closed'
export type ObjectType = 'hardware' | 'software' | 'account' | 'network' | 'resource'
export type RequestType =
  | 'troubleshooting'
  | 'maintenance'
  | 'resource_request'
  | 'permission_request'
  | 'usage_guidance'
  | 'policy_process'
export type DocumentStatus = 'queued' | 'processing' | 'ready' | 'failed'
export type IngestStage =
  | 'queued'
  | 'extracting'
  | 'chunking'
  | 'tagging'
  | 'embedding'
  | 'faq_extracting'
  | 'ready'
  | 'failed'
export type ContentType = 'pdf' | 'docx' | 'markdown' | 'txt'

export const OUT_OF_SCOPE_TEXT = '当前问题超出知识服务范围，你可以点击转人工。'
export const NO_KNOWLEDGE_TEXT = '现有知识无法回答。你可以点击转人工。'
export const WAIT_HUMAN_TEXT = '正在等待人工客服'
